

name: Math Utility Repo applying CI # Tên của nhóm công việc cần phải làm khi ai đó push code!

on:
  push:
    branches: [ "master" ] # Bất kì khi nào ai đó push code lên main
  pull_request:
    branches: [ "master" ] 

jobs: # Làm các việc ở dưới đây
  build:

    runs-on: ubuntu-latest       #1 Mượn 1 server của Mỹ, cài sẵn hệ điều hành Ubuntu

    steps:                       #2 Làm thêm các bước sau trên server vừa mượn
    - uses: actions/checkout@v3  #2.1 Lấy toàn bộ code từ kho chuyển sang server
    - name: Set up JDK 17        #2.2 Mượn JDK nào đó trên server, 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven     #2.3 Chuẩn bị chạy lệnh đóng gói app, chạy luôn Unit Test nếu có
      run: mvn -B package --file pom.xml
